version: "3.8"

services:
  backend:
    build:
      context: ./crypto_back_nestjs
      dockerfile: ../back.dockerfile
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=development
      - PORT=5050
  frontend:
    build:
      context: ./crypto_front
      dockerfile: ../front.dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
